# This config allows builds to upload build results to an s3 bucket (hubspot-blazar-artifacts)
# And have those served so that they can be read in a browser.

type: load_balancer
appRoot: /blazar-artifacts
team: hs-faas-infra

loadBalancers:
- privatehubteam

nginx:
  proxyConfig: |

    location ~* ^/blazar-artifacts/(.*) {
      set $url_full "$hs_env/$1";
      set $s3host hubspot-blazar-artifacts.s3.amazonaws.com;
      proxy_pass_header Server;
      proxy_set_header Host $s3host;
      proxy_redirect off;
      rewrite .* /$url_full break;

      access_by_lua_block {
        require("resty.aws").s3_set_headers(ngx.var.s3_hubspot_blazar_artifacts_access_key, ngx.var.s3_hubspot_blazar_artifacts_secret_key, ngx.var.s3host, ngx.var.uri)
      }
      proxy_pass             https://$s3host/$url_full;
    }

hublets:
  - NA1
