# HubSpot Deploy Settings
type: mixin

artifactBuildMetadata:
  organization: HubSpotProtected
  repository: Blazar
  module: BlazarService
  branch: staging

includeConfigs:
  - BlazarV2AllServiceCommon

buildResolution:
  qa:
    strategy: LATEST_BUILD
  prod:
    strategy: NO_BUILD

logging:
  level: INFO
  loggers:
    "com.hubspot.blazar":
      level: DEBUG
#    "org.skife.jdbi.v2":
#      level: TRACE
  appenders:
    - type: console
      logFormat: "%-5p [%d{ISO8601}] [%thread]: %c: %m%n%rEx"
    - type: sentry
      sentryDsn: https://2f002ad0745546b5b2b529461ca62349:a17da6ad912a4eec926c51a969925863@sentry.io/99138
      blazarRelease: "QA"

vaultAccessGroup: hs-paas-build-deploy

blazarConfiguration:
  executor:
    blazarApiDomain: "https://build.hubteamqa.com"
    blazarApiContextPath: "/blazar/v2"
  # Only build certain projects in QA
  whitelist: ['BlazarSmokeTests', 'jgoodwin-test-poms', 'blazar-test-hs-static', 'blazar-test-asset-bender', 'Blazar-IPB-Root', 'Blazar-IPB-Child1', 'Blazar-IPB-Child2']
  blacklist: []
  signalFx:
    authToken: RCvMukb4vXpVhKo_kI0HrQ
    defaultDataSourceName: BlazarV2QaService
    defaultDimensions:
      env: qa
      project: BlazarService

  slack_blazar:
    # creds for PI-BOT
    feedbackRoom: paas-b-d-feedback
    slackApiBaseUrl: https://slack.com/api
    slackApiToken: xoxb-15972715984-Vk684vJviuZYctLu2Twb54jm
    username: blazar-bot
    directMessageConfiguration:
      ignoredBranches: ["guava-moreobjects"]
      whitelistedUserEmails: []
      blacklistedUserEmails: ['rberdeen@hubspot.com']

  github:
    git.hubteam.com:
      oauthToken: 23804c65e210905e2b23bc4fd9c54aa4b3207e05
      setCommitStatus: false
      organizations:
        - HubSpot

  zookeeper:
    quorum: zk1.mesos_qa.iad02.hubinfraqa.com:2181,zk2.mesos_qa.iad02.hubinfraqa.com:2181,zk3.mesos_qa.iad02.hubinfraqa.com:2181
    namespace: "blazarv2qa"
    sessionTimeoutMillis: 60000
    connectTimeoutMillis: 5000

  database:
    driverClass: com.mysql.jdbc.Driver
    user: app_blazar
    password: "jYfuLb3qa#Yw"
    url: jdbc:mysql://db.blazarv2.hubteamqa.com:3306/BlazarV2

  ui:
    baseUrl: https://private.hubteamqa.com/blazar


  singularityClusters:
    Singularity3x3:
      safeToBuildWithoutNetworkLockDown: true
      host: bootstrap.hubteamqa.com
      path: /singularity/v2/api
      request: BlazarExecutorJavaTest-blazar-executor-java
      slaveHttpPort: 5051
    # Singularity-GCP-chs01:
    #   host: bootstrap.hubteamqa.com
    #   path: /singularity/gcp-chs01/api
    #   request: BlazarExecutorJavaTest-chs01-blazar-executor-java
    #   slaveHttpPort: 5051
    #   credentials:
    #     headerName: X-HubSpot-User
    #     token: jgoodwin
    SingularityProd3x4:
      host: bootstrap.hubteam.com
      path: /singularity/v3/api
      request: BlazarExecutorJavaTest-blazar-executor-java
      slaveHttpPort: 5051
