# HubSpot Deploy Settings
type: mixin

artifactBuildMetadata:
  organization: HubSpotProtected
  repository: Blazar
  module: BlazarService

team: hs-paas-build-deploy

trafficSplittingEnabled: false

slack:
- channelName: "#paas-build-deploy-notifications"
  all:
    preDeploy: MUTE
    success: NOTIFY
    failure: NOTIFY
    notifyForBlockerEvents: NOTIFY
    deployedNotRun: MUTE
  qa:
    success: MUTE
    failure: MUTE
    notifyForBlockerEvents: MUTE

env:
  all:
    VAULT_ACCESS_GROUP: hs-paas-build-deploy
    HS_ACCESS_GROUP: hs-paas-build-deploy
    JVM_EXTRA_MEMORY: 1024m
    EXTRA_ARGS: -Djute.maxbuffer=6291456 -Djava.net.preferIPv4Stack=true

zkGroup: blazar

buildResolution:
  qa:
    strategy: LATEST_BUILD
  prod:
    strategy: NO_BUILD

logging:
  level: INFO
  loggers:
    "com.hubspot.blazar":
      level: DEBUG
  appenders:
    - type: console
      logFormat: "%-5p [%d{ISO8601}] [%thread]: %c: %m%n%rEx"

vaultAccessGroup: hs-paas-build-deploy
